services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrix_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator-1:
    build:
      context: .
      dockerfile: samples/Orchestrix.Coordinator.Sample/Dockerfile
    environment:
      - ConnectionStrings__orchestrixdb=Host=postgres;Database=orchestrix_db;Username=postgres;Password=postgres
      - ConnectionStrings__redis=redis:6379
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Warning
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  coordinator-2:
    build:
      context: .
      dockerfile: samples/Orchestrix.Coordinator.Sample/Dockerfile
    environment:
      - ConnectionStrings__orchestrixdb=Host=postgres;Database=orchestrix_db;Username=postgres;Password=postgres
      - ConnectionStrings__redis=redis:6379
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Warning
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
